#!/usr/bin/env bash
# a bash script that displays best school 10 times and hi
# after the 9th iteration.

text="Best School"

i=0
while((i < 10)); do
	echo "$text"
	if ((i == 8));
	then
		echo "Hi"
	fi
	((i++))
done
